version: "2"

services:
  postgres:
    image: postgres:16-alpine
    container_name: vpn
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres