spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/donivpn
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration
server:
  port: 8080

telegram:
  bot:
    username: ${TG_BOT_USERNAME}
    password: ${TG_BOT_PASSWORD}
    token: ${TG_BOT_TOKEN}

feign:
  client:
    config:
      disable-ssl-validation: true
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

api:
  base-url: ${3UI_BASE_URL}
  username: ${TG_BOT_USERNAME}
  password: ${TG_BOT_PASSWORD}